name: IP Build & Simulation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Sim - RV_CPU
        run: ./build/builder.py -dut rv_cpu -sim -verify
